### ISSUE TITLE
Plan for programming ligatures/addtional features?

### ISSUE THREAD

**Issue by corelon** [jdw1996/epiphyte-mono#1]
Hi,

Congrats on your effort. I have already started test driving the font, and I can say so far I am quite pleased with the result, especially compared to the original liberation Mono.

Do you have any roadmap for the font?
Are you planning to support programming ligatures, like Fira Code?

I wish you happy new year.

BR,

Nikos

**Comment by jdw1996** [comment]
Thanks for the support!  As you may have seen in the README, this is my first time doing any work in font design, and so I am glad to hear others' opinions.

As of yesterday afternoon, I've done pretty much everything I was planning on doing.  I really like the alphanumeric characters in Liberation Mono, especially because they remain clear at such a small size, but I found some of the other characters unusable, and that is what I've attempted to fix with this font.

I don't like using fonts with ligatures, so I don't intend on adding them myself, but if you or someone you know is interested in working on them, that would be really cool.  It would probably make the most sense for the font with ligatures to exist in a fork, and I don't mind at all if anyone is interested in forking this repo.

In a perfect world, I would make the following changes, but I couldn't find shapes that I liked that still looked right in the context of the other characters:
* Curled tail on `l` in all faces (like DejaVu Sans Mono or Source Code Pro, to further differentiate from the number `1`)
* Curled tail on `i` in italics
* Single-storey `a` in italics
* Double-storey `g` in upright faces

If you have ideas of other changes you'd like to see, let me know and I can see what I can do; I would also be happy to welcome any other contributors.
